# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
  Version: '$(Major).$(Minor).$(Patch)'
  BN: $(Build.BuildNumber)
#  BI: $()
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Version); echo $(BN); echo $(name)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'AzureDevopsPipelineTest/*.sln'
    workingDirectory: 'AzureDevopsPipelineTest'
    configuration: $(buildConfiguration)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'AzureDevopsPipelineTest'
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Build.ArtifactStagingDirectory); ls $(Build.ArtifactStagingDirectory); echo $(Build.ArtifactStagingDirectory)/Ormico.AzureDevopsPipelineTest/bin/*'
