trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
#  Patch: '0'
  Patch: $(Build.BuildId)
  Version: '$(Major).$(Minor).$(Patch)'
#  Version: '$(Major).$(Minor).$(Build.BuildNumber)'
  BN: $(Build.BuildNumber)
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Version); echo $(BN); echo $(name)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'AzureDevopsPipelineTest/*.sln'
    workingDirectory: 'AzureDevopsPipelineTest'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#- bash: ls $(Build.StagingDirectory)/*.nupkg
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nuget-artifacts