# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
  Version: '$(Major).$(Minor).$(Patch)'
  BN: $(Build.BuildNumber)
#  BI: $()
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $(Version); echo $(BN); echo $(rev:.r)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'AzureDevopsPipelineTest/*.sln'
    workingDirectory: 'AzureDevopsPipelineTest'
    configuration: $(buildConfiguration)
- task: DotNetCoreCLI@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    workingDirectory: 'AzureDevopsPipelineTest'
- task: DotNetCoreCLI@2
  inputs:
    command: push
    projects: '**/*.nupkg'
    workingDirectory: 'AzureDevopsPipelineTest/Ormico.AzureDevopsPipelineTest.CLI/bin/$(buildConfiguration)/Ormico.AzureDevopsPipelineTest.CLI.1.0.0.nupkg'
